#!/bin/bash

W3MIMGDISPLAY="/usr/lib/w3m/w3mimgdisplay"
FONTH=15 # Size of one terminal row
FONTW=7 # Size of one terminal column

pane_left=$(tmux display-message -p '#{pane_left}')
pane_top=$(tmux display-message -p '#{pane_top}')

X=$1
Y=$2
X=$((X + pane_left))
Y=$((Y + pane_top))
COLUMNS=$3
LINES=$4

x=$((FONTW * X))
y=$((FONTH * Y))

erase="6;$x;$y;$(( FONTW*COLUMNS ));$(( FONTH*LINES ))\n3;"
echo -e "$erase" | $W3MIMGDISPLAY
